### ISSUE TITLE
Plz provide an on-line demo!

### ISSUE THREAD

**Issue by mileskin** [infews/keydown#1]
I managed to find https://github.com/infews/2010.09.29.SeleniumSF.Jasmine which looks great but an on-line demo would be great for showing/promoting the stuff to other people. Link related: http://twitter.com/#!/teelahti/status/10224000085004288

Thanks & cheers,

Miki Leskinen (aka @mileskin)

**Comment by andrewhavens** [comment]
I agree! A simple demo of what a presentation would look like would be extremely beneficial.

**Comment by raid5** [comment]
+1 for a demo. It was the first thing I looked for in the README.

**Comment by jeffpoulton** [comment]
+2 for a demo. Although the first place I looked was in the project description at the top of the page. I love when projects have a link to the homepage or demo page right there.
