### ISSUE TITLE
background images gone?

### ISSUE THREAD

**Issue by yihui** [infews/keydown#10]
in 0.9.0, background images by `}}} filename` seem to be gone; I cannot see them anymore...

BTW, I think the default theme is much less appealing than the previous version; it is almost "plain text" now.

**Comment by infews** [comment]
Background images should still be there. It's likely a bug on my merge back into master.

As for the themes, it currently defaults to using one of the 3 deck.js themes. This is changeable within your presentation directory. I do have stories in my backlog to a) document how better to change it and b) offer a 'better' standard theme.

**Comment by infews** [comment]
Fixed. Pushed 0.9.1
