### ISSUE TITLE
Can you use an Apple remote?

### ISSUE THREAD

**Issue by mjones-rpx** [infews/keydown#13]
Quick question: does keydown handle forward/backward commands from an Apple remote? Has anyone done this?

**Comment by ghost** [comment]
I've installed [Mira](http://twistedmelon.com/mira/) and assigned the keys for left / right on Firefox. Works just fine...

**Comment by infews** [comment]
This is not a Keydown concern. It's the Browser and Apple Remote.

I've found the best remote to use is one of the ones from Logitech. They map to browser just fine.
