### ISSUE TITLE
Is it possible to align differently only "chunk" of a slide?

### ISSUE THREAD

**Issue by adinapoli** [infews/keydown#24]
For example, starting with a !SLIDE left and then have some piece of syntax to align a part of the same slide (inventing):

```
 !ALIGN center 
##My aligned content
```

**Comment by infews** [comment]
You should be able to do that with some custom CSS. The complexity of adding that to the mardkown syntax is beyond the scope of this tool. CSS and Deck.js themes can handle this better.
