### ISSUE TITLE
are you really using Pygments for highlighting?

### ISSUE THREAD

**Issue by yihui** [infews/keydown#9]
what I see in the source code is `CodeRay` instead of `Pygments` as documented... the latter seems to support much more languages; I was struggling with one language (R) listed in the support list of Pygments, but it could not be highlighted with keydown.

**Comment by infews** [comment]
The short answer is yes, I moved from Pygments to CodeRay to ease development/installation. The longer answer is that I'm in the process of moving to using deck.js, which uses codemirror.js to do highlighting. When I release 1.0 the docs will reflect all of this.

**Comment by yihui** [comment]
Cool! Looking forward to the update with deck.js!

Thanks!
